<?php
// Dados dos 12 Apóstolos

$apostles = [
    [
        'id' => 'peter',
        'name' => 'Pedro',
        'title' => 'O Líder Impulsivo',
        'emoji' => '⚓',
        'image' => '/assets/images/peter.png',
        'motto' => 'Fé em ação',
        'axes' => ['AC' => 9, 'RE' => 7, 'LS' => 9, 'ER' => 8, 'IP' => 6, 'CC' => 8],
        'summary' => 'Pedro é o apóstolo da liderança corajosa. Impulsivo e destemido, você age primeiro e pensa depois. Sua força vem da confiança inabalável, mas sua fraqueza é a precipitação.',
        'biblicalRef' => '1 Pedro 1:3-5',
        'biblicalText' => 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que nos abençoou com toda sorte de bênção espiritual nos lugares celestiais em Cristo.',
        'strengths' => [
            ['title' => 'Liderança Natural', 'description' => 'Você naturalmente inspira e guia os outros'],
            ['title' => 'Coragem Inabalável', 'description' => 'Enfrenta desafios sem medo'],
            ['title' => 'Fé Profunda', 'description' => 'Acredita contra todas as probabilidades'],
            ['title' => 'Ação Decisiva', 'description' => 'Toma decisões rapidamente'],
            ['title' => 'Autenticidade', 'description' => 'Genuíno em tudo que faz'],
        ],
        'blindSpots' => [
            ['title' => 'Impulsividade', 'description' => 'Age sem pensar nas consequências'],
            ['title' => 'Rigidez', 'description' => 'Difícil de mudar de opinião uma vez decidido'],
            ['title' => 'Falta de Paciência', 'description' => 'Quer resultados imediatos'],
            ['title' => 'Arrogância', 'description' => 'Confia demais em suas próprias forças'],
        ],
        'growthAdvice' => 'Aprenda a pausar antes de agir. Sua impulsividade é uma força quando canalizada com sabedoria, mas uma fraqueza quando descontrolada.',
    ],
    [
        'id' => 'john',
        'name' => 'João',
        'title' => 'O Discípulo Amado',
        'emoji' => '❤️',
        'image' => '/assets/images/john.png',
        'motto' => 'Amor acima de tudo',
        'axes' => ['AC' => 3, 'RE' => 9, 'LS' => 4, 'ER' => 5, 'IP' => 8, 'CC' => 9],
        'summary' => 'João é o apóstolo do amor contemplativo. Profundo, emocional e intuitivo, você procura significado espiritual em tudo. Sua compaixão é seu maior dom.',
        'biblicalRef' => 'João 13:34-35',
        'biblicalText' => 'Um novo mandamento vos dou: que vos ameis uns aos outros; assim como eu vos amei, que vós também vos ameis uns aos outros.',
        'strengths' => [
            ['title' => 'Empatia Profunda', 'description' => 'Entende e sente o que os outros sentem'],
            ['title' => 'Intuição Espiritual', 'description' => 'Conecta-se facilmente com o divino'],
            ['title' => 'Amor Genuíno', 'description' => 'Ama incondicionalmente'],
            ['title' => 'Sabedoria Contemplativa', 'description' => 'Reflete profundamente sobre a vida'],
            ['title' => 'Lealdade Infinita', 'description' => 'Fiel ao lado de quem ama'],
        ],
        'blindSpots' => [
            ['title' => 'Passividade', 'description' => 'Evita confronto e ação direta'],
            ['title' => 'Melancolia', 'description' => 'Tender à tristeza e ao isolamento'],
            ['title' => 'Idealismo Ingênuo', 'description' => 'Espera dos outros o que poucos conseguem dar'],
            ['title' => 'Falta de Discernimento Prático', 'description' => 'Não vê detalhes mundanos'],
        ],
        'growthAdvice' => 'Equilibre sua profundidade emocional com ação. Não é preciso estar perfeito para servir.',
    ],
    [
        'id' => 'james_greater',
        'name' => 'Tiago Maior',
        'title' => 'O Zeloso',
        'emoji' => '⚡',
        'image' => '/assets/images/james_greater.png',
        'motto' => 'Paixão pela verdade',
        'axes' => ['AC' => 8, 'RE' => 6, 'LS' => 7, 'ER' => 9, 'IP' => 7, 'CC' => 6],
        'summary' => 'Tiago é o apóstolo da paixão e dedicação. Fervoroso e comprometido, você coloca toda sua energia em suas convicções. Sua lealdade é inabalável, mas sua intensidade pode ser amedrontadora.',
        'biblicalRef' => 'Marcos 10:38-39',
        'biblicalText' => 'Mas Jesus lhes disse: "Vocês não sabem o que estão pedindo. Conseguem beber o cálice que eu bebo ou serem batizados com o batismo com que sou batizado?"',
        'strengths' => [
            ['title' => 'Dedicação Total', 'description' => 'Comprometido até o fim'],
            ['title' => 'Fé Inabalável', 'description' => 'Não se desvia de suas convicções'],
            ['title' => 'Coragem Guerreira', 'description' => 'Enfrenta oposição sem medo'],
            ['title' => 'Inspiração Contagiante', 'description' => 'Sua paixão motiva outros'],
            ['title' => 'Autossacrifício', 'description' => 'Abre mão por suas crenças'],
        ],
        'blindSpots' => [
            ['title' => 'Intolerância', 'description' => 'Dificuldade de aceitar opiniões diferentes'],
            ['title' => 'Impulsividade Agressiva', 'description' => 'Pode ser violento em defesa da fé'],
            ['title' => 'Falta de Flexibilidade', 'description' => 'Preto ou branco, nada cinzento'],
            ['title' => 'Severidade', 'description' => 'Pouca compaixão por fraquezas alheias'],
        ],
        'growthAdvice' => 'Sua paixão é um presente, mas aprenda a expressa-la com sabedoria e compaixão.',
    ],
    [
        'id' => 'andrew',
        'name' => 'André',
        'title' => 'O Ponte',
        'emoji' => '🤝',
        'image' => '/assets/images/andrew.png',
        'motto' => 'Conectando pessoas',
        'axes' => ['AC' => 5, 'RE' => 6, 'LS' => 8, 'ER' => 7, 'IP' => 5, 'CC' => 7],
        'summary' => 'André é o apóstolo da conexão. Você vê potencial nos outros e adora conectá-los. Amigável e observador, você é a ponte que une as pessoas. Seu risco é perder sua própria voz.',
        'biblicalRef' => 'João 1:40-42',
        'biblicalText' => 'André, irmão de Simão Pedro, era um dos dois que tinham ouvido o testemunho de João e tinham seguido Jesus.',
        'strengths' => [
            ['title' => 'Dom de Conexão', 'description' => 'Naturalmente conecta pessoas certas'],
            ['title' => 'Sensibilidade', 'description' => 'Percebe necessidades alheias'],
            ['title' => 'Humildade', 'description' => 'Não precisa do destaque'],
            ['title' => 'Facilitador', 'description' => 'Cria espaço para outros brilharem'],
            ['title' => 'Discernimento', 'description' => 'Enxerga potencial oculto'],
        ],
        'blindSpots' => [
            ['title' => 'Falta de Liderança', 'description' => 'Hesita em tomar a frente'],
            ['title' => 'Indecisão', 'description' => 'Demora para fazer escolhas'],
            ['title' => 'Invisibilidade', 'description' => 'Sua contribuição passa despercebida'],
            ['title' => 'Dependência', 'description' => 'Precisa da validação dos outros'],
        ],
        'growthAdvice' => 'Sua modéstia é virtude, mas também pode ser um obstáculo. Deixe sua luz brilhar.',
    ],
    [
        'id' => 'philip',
        'name' => 'Filipe',
        'title' => 'O Pragmático',
        'emoji' => '💼',
        'image' => '/assets/images/philip.png',
        'motto' => 'Planejamento é tudo',
        'axes' => ['AC' => 7, 'RE' => 5, 'LS' => 6, 'ER' => 4, 'IP' => 3, 'CC' => 8],
        'summary' => 'Filipe é o apóstolo do detalhe e planejamento. Você é metódico, lógico e prático. Seu desafio é aprender a confiar além das evidências visíveis.',
        'biblicalRef' => 'João 6:7',
        'biblicalText' => 'Filipe respondeu: "Nem duzentos denários de pão seriam suficientes para que cada um recebesse um pouco."',
        'strengths' => [
            ['title' => 'Atenção ao Detalhe', 'description' => 'Nada escapa sua atenção'],
            ['title' => 'Pensamento Lógico', 'description' => 'Resolve problemas de forma sistemática'],
            ['title' => 'Praticidade', 'description' => 'Foca em soluções realizáveis'],
            ['title' => 'Confiabilidade', 'description' => 'Cumpre o que promete'],
            ['title' => 'Organização', 'description' => 'Tudo tem seu lugar'],
        ],
        'blindSpots' => [
            ['title' => 'Falta de Fé', 'description' => 'Quer evidências para tudo'],
            ['title' => 'Rigidez Lógica', 'description' => 'Dificuldade com mistério e ambiguidade'],
            ['title' => 'Pessimismo', 'description' => 'Vê obstáculos antes de possibilidades'],
            ['title' => 'Falta de Criatividade', 'description' => 'Preso ao que é conhecido'],
        ],
        'growthAdvice' => 'Seu pragmatismo é valioso, mas nem tudo pode ser calculado. Aprenda a sonhar.',
    ],
    [
        'id' => 'bartholomew',
        'name' => 'Bartolomeu',
        'title' => 'O Crítico Sincero',
        'emoji' => '🔍',
        'image' => '/assets/images/bartholomew.png',
        'motto' => 'Verdade sem filtro',
        'axes' => ['AC' => 4, 'RE' => 8, 'LS' => 3, 'ER' => 6, 'IP' => 4, 'CC' => 9],
        'summary' => 'Bartolomeu é o apóstolo da verdade descomprometida. Você vê através das mentiras e hipocrisia. Seu desafio é aprender a comunicar verdades com graça.',
        'biblicalRef' => 'João 1:47',
        'biblicalText' => 'Jesus viu Natanael aproximando-se e disse a seu respeito: "Eis aqui um verdadeiro israelita, em quem não há dolo."',
        'strengths' => [
            ['title' => 'Honestidade Radical', 'description' => 'Não teme dizer a verdade'],
            ['title' => 'Discernimento Profundo', 'description' => 'Vê além das aparências'],
            ['title' => 'Integridade Inabalável', 'description' => 'Coerência entre palavras e ações'],
            ['title' => 'Defensor da Verdade', 'description' => 'Não permite injustiça silenciosa'],
            ['title' => 'Análise Crítica', 'description' => 'Questiona presupostos'],
        ],
        'blindSpots' => [
            ['title' => 'Cinismo', 'description' => 'Desconfiança excessiva das intenções'],
            ['title' => 'Falta de Empatia', 'description' => 'Verdade sem compaixão machuca'],
            ['title' => 'Isolamento', 'description' => 'Sua honestidade afasta pessoas'],
            ['title' => 'Julgamento', 'description' => 'Rápido em condenar'],
        ],
        'growthAdvice' => 'Sua verdade é necessária, mas aprenda a entregar-la com amor e sabedoria.',
    ],
    [
        'id' => 'matthew',
        'name' => 'Mateus',
        'title' => 'O Transformado',
        'emoji' => '📖',
        'image' => '/assets/images/matthew.png',
        'motto' => 'Vidas mudadas para sempre',
        'axes' => ['AC' => 6, 'RE' => 7, 'LS' => 7, 'ER' => 5, 'IP' => 7, 'CC' => 6],
        'summary' => 'Mateus é o apóstolo da transformação radical. Seu passado não define seu futuro. Você acredita no poder de uma segunda chance e dedica sua vida a ajudar outros a encontrá-la.',
        'biblicalRef' => 'Mateus 9:9-13',
        'biblicalText' => 'Jesus viu um homem chamado Mateus assentado na coletoria; e disse-lhe: Segue-me. E levantando-se, o seguiu.',
        'strengths' => [
            ['title' => 'Redenção Pessoal', 'description' => 'Viveu transformação profunda'],
            ['title' => 'Compaixão pelos Marginalizados', 'description' => 'Entende quem foi rejeitado'],
            ['title' => 'Comunicação Clara', 'description' => 'Sabe contar histórias que transformam'],
            ['title' => 'Fé em Pessoas', 'description' => 'Acredita em potencial oculto'],
            ['title' => 'Humildade Genuína', 'description' => 'Não se esquece de onde veio'],
        ],
        'blindSpots' => [
            ['title' => 'Passado Assombrador', 'description' => 'Culpa que nunca se dissipa completamente'],
            ['title' => 'Falta de Confiança', 'description' => 'Dúvida sobre seu próprio valor'],
            ['title' => 'Desejo de Aprovação Excessivo', 'description' => 'Tenta compensar demais'],
            ['title' => 'Perfectcionismo', 'description' => 'Quer provar que mudou'],
        ],
        'growthAdvice' => 'Você já é perdoado. Seu transformação é real. Agora aprenda a viver nesta verdade completamente.',
    ],
    [
        'id' => 'thomas',
        'name' => 'Tomé',
        'title' => 'O Desconfiado',
        'emoji' => '❓',
        'image' => '/assets/images/thomas.png',
        'motto' => 'Preciso ver para crer',
        'axes' => ['AC' => 5, 'RE' => 8, 'LS' => 4, 'ER' => 4, 'IP' => 2, 'CC' => 8],
        'summary' => 'Tomé é o apóstolo da dúvida honesta. Você não aceita fé cega. Seu desafio é aprender que nem tudo pode ser provado, mas ainda assim pode ser verdadeiro.',
        'biblicalRef' => 'João 20:24-29',
        'biblicalText' => 'Disse-lhe Jesus: Bem-aventurados aqueles que não viram e creram.',
        'strengths' => [
            ['title' => 'Pensamento Crítico', 'description' => 'Questiona antes de aceitar'],
            ['title' => 'Rigor Intelectual', 'description' => 'Busca evidências sólidas'],
            ['title' => 'Honestidade Intelectual', 'description' => 'Não fingir compreensão falsa'],
            ['title' => 'Fé Conquistada', 'description' => 'Quando crê, é com profundidade'],
            ['title' => 'Realismo', 'description' => 'Pés no chão'],
        ],
        'blindSpots' => [
            ['title' => 'Cinismo Paralisante', 'description' => 'Desconfiança que impede ação'],
            ['title' => 'Isolamento Emocional', 'description' => 'Prote-se com ceticismo'],
            ['title' => 'Falta de Coragem', 'description' => 'Medo de estar errado'],
            ['title' => 'Paralisia Analítica', 'description' => 'Análise infinita sem conclusão'],
        ],
        'growthAdvice' => 'Sua dúvida pode levar a sabedoria ou ao desespero. Escolha questionar com esperança, não com desespero.',
    ],
    [
        'id' => 'james_lesser',
        'name' => 'Tiago Menor',
        'title' => 'O Pilar Discreto',
        'emoji' => '🏛️',
        'image' => '/assets/images/james_lesser.png',
        'motto' => 'Fé em obras',
        'axes' => ['AC' => 6, 'RE' => 7, 'LS' => 8, 'ER' => 5, 'IP' => 4, 'CC' => 7],
        'summary' => 'Tiago é o apóstolo da fé prática. Você não fala muito, mas suas ações falam volumes. Seu desafio é aprender que às vezes a voz precisa ser ouvida.',
        'biblicalRef' => 'Tiago 1:22',
        'biblicalText' => 'Assim também a fé, se não tiver as obras, é morta em si mesma.',
        'strengths' => [
            ['title' => 'Liderança Discreta', 'description' => 'Guia sem buscar destaque'],
            ['title' => 'Fé Viva', 'description' => 'Demonstra fé através de ações'],
            ['title' => 'Estabilidade', 'description' => 'Confiável e consistente'],
            ['title' => 'Profundidade', 'description' => 'Reflexão séria sobre significado'],
            ['title' => 'Justiça Social', 'description' => 'Trabalha pelos fracos'],
        ],
        'blindSpots' => [
            ['title' => 'Invisibilidade', 'description' => 'Contribuição não é reconhecida'],
            ['title' => 'Falta de Voz', 'description' => 'Não comunica bem suas ideias'],
            ['title' => 'Perfeccionismo', 'description' => 'Espera perfeição das ações'],
            ['title' => 'Rigidez Moral', 'description' => 'Julgamento baseado em legalismo'],
        ],
        'growthAdvice' => 'Seu exemplo é poderoso, mas a palavra também importa. Encontre sua voz.',
    ],
    [
        'id' => 'simon_zelotes',
        'name' => 'Simão Zelota',
        'title' => 'O Revolucionário',
        'emoji' => '🔥',
        'image' => '/assets/images/simon_zelotes.png',
        'motto' => 'Mudança radical',
        'axes' => ['AC' => 8, 'RE' => 5, 'LS' => 6, 'ER' => 9, 'IP' => 8, 'CC' => 5],
        'summary' => 'Simão é o apóstolo da paixão revolucionária. Você vê injustiça e quer mudar o mundo. Seu desafio é aprender que verdadeira transformação é frequentemente lenta e gradual.',
        'biblicalRef' => 'Lucas 6:15',
        'biblicalText' => 'Simão, chamado Zelota, e Judas filho de Tiago.',
        'strengths' => [
            ['title' => 'Visão de Mudança', 'description' => 'Vê possibilidades de transformação'],
            ['title' => 'Paixão Ativista', 'description' => 'Move-se por convicção profunda'],
            ['title' => 'Coragem de Confrontar', 'description' => 'Desafia o status quo'],
            ['title' => 'Energia Contagiante', 'description' => 'Inspira ação em outros'],
            ['title' => 'Idealismo Nobre', 'description' => 'Acredita em mundo melhor'],
        ],
        'blindSpots' => [
            ['title' => 'Impaciência', 'description' => 'Quer mudança rápida demais'],
            ['title' => 'Intolerância', 'description' => 'Dificuldade com quem pensa diferente'],
            ['title' => 'Dogmatismo', 'description' => 'Toma posição absoluta'],
            ['title' => 'Alienação', 'description' => 'Sua radicalidade afasta moderados'],
        ],
        'growthAdvice' => 'Sua paixão pode mudar o mundo, mas só se aprender a trabalhar com quem não compartilha toda sua raiva.',
    ],
    [
        'id' => 'judas_thaddaeus',
        'name' => 'Judas Tadeu',
        'title' => 'O Questionador de Fé',
        'emoji' => '🤔',
        'image' => '/assets/images/judas_thaddaeus.png',
        'motto' => 'Fé com perguntas',
        'axes' => ['AC' => 4, 'RE' => 8, 'LS' => 6, 'ER' => 6, 'IP' => 5, 'CC' => 7],
        'summary' => 'Judas é o apóstolo que questiona mantendo fé. Você não tem respostas fáceis, mas continua buscando. Seu desafio é aprender a viver com ambiguidade.',
        'biblicalRef' => 'João 14:22',
        'biblicalText' => 'Perguntou-lhe Judas (não o Iscariotes): Senhor, como é que se há de manifestar a nós e não ao mundo?',
        'strengths' => [
            ['title' => 'Fé Reflexiva', 'description' => 'Questiona de forma honesta'],
            ['title' => 'Busca de Significado', 'description' => 'Procura entendimento profundo'],
            ['title' => 'Compreensão Nuançada', 'description' => 'Vê complexidade nos problemas'],
            ['title' => 'Diálogo Honesto', 'description' => 'Conversa aberta com Deus'],
            ['title' => 'Tolerância à Ambiguidade', 'description' => 'Convive com mistério'],
        ],
        'blindSpots' => [
            ['title' => 'Indecisão Crônica', 'description' => 'Paralisia por questionamento'],
            ['title' => 'Confusão Espiritual', 'description' => 'Muitas perguntas, poucas respostas'],
            ['title' => 'Alienação Intelectual', 'description' => 'Isolamento em seus questionamentos'],
            ['title' => 'Falta de Ação', 'description' => 'Reflexão sem movimento'],
        ],
        'growthAdvice' => 'Suas perguntas são válidas. Mas aprenda que às vezes a fé vai além da compreensão.',
    ],
    [
        'id' => 'matthew_apostle',
        'name' => 'Matias',
        'title' => 'O Escolhido em Segundo Plano',
        'emoji' => '✨',
        'image' => '/assets/images/matthew.png',
        'motto' => 'Oportunidade inesperada',
        'axes' => ['AC' => 6, 'RE' => 6, 'LS' => 7, 'ER' => 6, 'IP' => 5, 'CC' => 7],
        'summary' => 'Matias é o apóstolo da redenção inesperada. Você aparece quando menos se espera e faz diferença. Seu desafio é aprender a ter confiança em seu chamado único.',
        'biblicalRef' => 'Atos 1:23-26',
        'biblicalText' => 'E apontaram a dois: José chamado Barsabás, cognominado Justo, e Matias. E orando, disseram: Tu, Senhor, que conheces os corações de todos, mostra qual destes dois elegeste.',
        'strengths' => [
            ['title' => 'Disposição', 'description' => 'Pronto para servir quando chamado'],
            ['title' => 'Humildade', 'description' => 'Aceita papel em segundo plano'],
            ['title' => 'Flexibilidade', 'description' => 'Adapta-se a novos papéis'],
            ['title' => 'Lealdade', 'description' => 'Completamente dedicado'],
            ['title' => 'Confiança', 'description' => 'Acredita que foi escolhido'],
        ],
        'blindSpots' => [
            ['title' => 'Invisibilidade Aceitada', 'description' => 'Muito contente em ficar sombra'],
            ['title' => 'Falta de Iniciativa', 'description' => 'Espera antes de agir'],
            ['title' => 'Insegurança Latente', 'description' => 'Questiona seu próprio valor'],
            ['title' => 'Dependência de Validação', 'description' => 'Precisa ser "escolhido"'],
        ],
        'growthAdvice' => 'Você foi escolhido. Agora aprenda a liderar mesmo que de forma discreta.',
    ],
    [
        'id' => 'judas_iscariot',
        'name' => 'Judas Iscariotes',
        'title' => 'O Traidor Perdido',
        'emoji' => '⚰️',
        'image' => '/assets/images/judas_iscariot.png',
        'motto' => 'Remorso sem redenção',
        'axes' => ['AC' => 7, 'RE' => 4, 'LS' => 2, 'ER' => 8, 'IP' => 6, 'CC' => 3],
        'summary' => 'Judas é o apóstolo da queda e da traição. Você luta com ganância, inveja e falta de verdadeira conexão. Seu desafio é aprender que nem todo erro é irreversível.',
        'biblicalRef' => 'Mateus 26:14-16',
        'biblicalText' => 'Então um dos doze, chamado Judas Iscariotes, foi ter com os príncipes dos sacerdotes, e disse-lhes: Que me quereis dar, e eu vo-lo entregarei?',
        'strengths' => [
            ['title' => 'Inteligência Financeira', 'description' => 'Bom com números e recursos'],
            ['title' => 'Capacidade Analítica', 'description' => 'Vê detalhes que outros perdem'],
            ['title' => 'Coragem de Questionar', 'description' => 'Não tem medo de confrontar'],
            ['title' => 'Emoção Intensa', 'description' => 'Sente profundamente'],
            ['title' => 'Remorso', 'description' => 'Consciência de seus erros'],
        ],
        'blindSpots' => [
            ['title' => 'Traição Fundamental', 'description' => 'Incapaz de verdadeira lealdade'],
            ['title' => 'Ganância Desenfreada', 'description' => 'Sempre quer mais'],
            ['title' => 'Solidão Escolhida', 'description' => 'Não deixa ninguém perto'],
            ['title' => 'Desespero Sem Esperança', 'description' => 'Vê apenas ruína à frente'],
        ],
        'growthAdvice' => 'Seu remorso é real, mas pode levar à redenção ou ao desespero. O fim de sua história ainda não foi escrito.',
    ],
];

function getApostleById($id) {
    global $apostles;
    return array_values(array_filter($apostles, fn($a) => $a['id'] === $id))[0] ?? null;
}

function getAllApostles() {
    global $apostles;
    return $apostles;
}
